# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/example/proto/message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fsrc/example/proto/message.proto\x12\x04test\"1\n\x07Visitor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03sex\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"4\n\x06Ticket\x12\x14\n\x0cqueue_number\x18\x01 \x01(\x05\x12\x14\n\x0cwelcome_text\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.example.proto.message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_VISITOR']._serialized_start=41
  _globals['_VISITOR']._serialized_end=90
  _globals['_TICKET']._serialized_start=92
  _globals['_TICKET']._serialized_end=144
# @@protoc_insertion_point(module_scope)
