"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Visitor(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    SEX_FIELD_NUMBER: builtins.int
    AGE_FIELD_NUMBER: builtins.int
    name: builtins.str
    sex: builtins.str
    age: builtins.int
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        sex: builtins.str = ...,
        age: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["age", b"age", "name", b"name", "sex", b"sex"]) -> None: ...

global___Visitor = Visitor

@typing_extensions.final
class Ticket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUEUE_NUMBER_FIELD_NUMBER: builtins.int
    WELCOME_TEXT_FIELD_NUMBER: builtins.int
    queue_number: builtins.int
    welcome_text: builtins.str
    def __init__(
        self,
        *,
        queue_number: builtins.int = ...,
        welcome_text: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["queue_number", b"queue_number", "welcome_text", b"welcome_text"]) -> None: ...

global___Ticket = Ticket
